spring:
  security: # 配置注册中心账号密码
    user:
      name: root
      password: Rqwd2345
server:
  port: 8801
  tomcat:
    basedir: /home/tmp
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:Rqwd2345@localhost:${server.port}/eureka/
    register-with-eureka: true
    fetch-registry: false
    registry-fetch-interval-seconds: 5
  instance:
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
#日志保存路径
log:
  path: /hic-java_log/eureke
logging:
  config: classpath:logback-custom.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always